# Data path. adjust them!
common:
    image_path:  "/home/mars_ugv/catkin_ws/src/livox_camera_calib/png"
    pcd_path:  "/home/mars_ugv/catkin_ws/src/livox_camera_calib/pcd"
    result_path:  "/home/mars_ugv/catkin_ws/src/livox_camera_calib/result/extrinsic.txt"
    data_num: 2
# Camera Parameters. Adjust them!
camera:
    camera_matrix: [1130.011805, 0.000000, 997.515249,
                    0.000000, 1130.386363, 594.610762,
                    0.000000, 0.000000, 1.000000]
    dist_coeffs: [0.037991, -0.054455, 0.002211, 0.003054, 0.000000]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/mars_ugv/catkin_ws/src/livox_camera_calib/config/config_outdoor.yaml"
    use_rough_calib: false # set true if your initial_extrinsic is bad
