# Data path. adjust them!
common:
    image_path:  "/home/mars_ugv/catkin_ws/src/livox_camera_calib/png"
    pcd_path:  "/home/mars_ugv/catkin_ws/src/livox_camera_calib/pcd"
    result_path:  "/home/mars_ugv/catkin_ws/src/livox_camera_calib/result/extrinsic.txt"
    data_num: 3
# Camera Parameters. Adjust them!
camera:
    camera_matrix: [1140.274143, 0.000000, 995.512597,
                    0.000000, 1138.685376, 576.140897,
                    0.000000, 0.000000, 1.000000]
    dist_coeffs: [0.043826, -0.058038, -0.001744, -0.000374, 0.000000]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/mars_ugv/catkin_ws/src/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
